[package]
name = "gsnake-core"
version.workspace = true
edition.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
ts-rs.workspace = true

[dev-dependencies]
proptest = "1.6"

[lib]
crate-type = ["lib"]
